export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const FETCH_ALL_COUNTRIES = 'FETCH_ALL_COUNTRIES';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const FAVORITE_COUNTRY = 'FAVORITE_COUNTRY';
